a={1,2,3,4}
b={4,5,6,7}
c={0,2,4,6,8}
d={2,3}
print(type(a))
a.add(3)
print(a)
o=a.copy()
print(o)
a.pop()
print(a)
d.remove(2)
d.discard(100)
print(d)
f=a|b|c|d
print(f)
e=a.union(b)
print(e)
g=a-b-c-d
print(g)
h=a.difference(b)
print(h)
h.difference_update(a)
print(h)
i=a&b&c&d
print(i)
j=a.intersection(b)
print(j)
k=a.symmetric_difference(c)
print(k)
k.symmetric_difference_update(j)
print(k)
t=h.difference_update(c)
print(t)
aa={0,1,2,3,4,5,6,7}
bb={0,2,4,6}
cc={1,3,5,7}
print(aa.issuperset(bb))
print(cc.issubset(aa))
print(aa.isdisjoint(bb))
dd=aa^bb
print(dd)
aa.clear()
print(aa)